name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Set execute permissions
        run: chmod +x ./scripts/deploy.sh

      - name: Run script
        run: ./scripts/deploy.sh
